home:
    resource: ../../src/Home/Action/
    type: annotation
auth:
    resource: ../../src/Auth/Action/
    type: annotation
trick:
    resource: ../../src/Trick/Action/
    type: annotation
chat:
    resource: ../../src/Chat/Action/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
