<?php

namespace ContainerHxdSKzR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHomePageService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Home\Action\HomePage' shared autowired service.
     *
     * @return \App\Home\Action\HomePage
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'_Core'.\DIRECTORY_SEPARATOR.'Action'.\DIRECTORY_SEPARATOR.'ActionInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Home'.\DIRECTORY_SEPARATOR.'Action'.\DIRECTORY_SEPARATOR.'HomePage.php';

        $container->services['App\\Home\\Action\\HomePage'] = $instance = new \App\Home\Action\HomePage();

        $instance->setContainer(($container->privates['.service_locator.5nX7ca3'] ?? $container->load('get_ServiceLocator_5nX7ca3Service'))->withContext('App\\Home\\Action\\HomePage', $container));

        return $instance;
    }
}
