<?php

namespace ContainerHxdSKzR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoginService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Auth\Action\Login' shared autowired service.
     *
     * @return \App\Auth\Action\Login
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'_Core'.\DIRECTORY_SEPARATOR.'Action'.\DIRECTORY_SEPARATOR.'ActionInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Auth'.\DIRECTORY_SEPARATOR.'Action'.\DIRECTORY_SEPARATOR.'Login.php';

        $container->services['App\\Auth\\Action\\Login'] = $instance = new \App\Auth\Action\Login();

        $instance->setContainer(($container->privates['.service_locator.5nX7ca3'] ?? $container->load('get_ServiceLocator_5nX7ca3Service'))->withContext('App\\Auth\\Action\\Login', $container));

        return $instance;
    }
}
