<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVNxUe4x\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVNxUe4x/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVNxUe4x.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVNxUe4x\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVNxUe4x\App_KernelDevDebugContainer([
    'container.build_hash' => 'VNxUe4x',
    'container.build_id' => '92bc63f4',
    'container.build_time' => 1608421700,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVNxUe4x');
