<?php

// This file was generated by running "composer dump-env test"

return array (
  'APP_ENV' => 'test',
  'APP_SECRET' => '$ecretf0rt3st',
  'APP_LOCALE' => 'fr',
  'MAILER_DSN' => 'smtp://studio.flashbang@gmail.com:kmapdpoburjakjig@smtp.gmail.com:587',
  'DATABASE_URL' => 'mysql://root:toor@mariadb:3306/snowtricks?serverVersion=mariadb-10.5.5',
  'KERNEL_CLASS' => 'App\\Kernel',
  'SYMFONY_DEPRECATIONS_HELPER' => '999999',
  'PANTHER_APP_ENV' => 'panther',
);
