<?php

namespace ContainerVNxUe4x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSignPageService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Auth\Action\SignPage' shared autowired service.
     *
     * @return \App\Auth\Action\SignPage
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Auth/Action/SignPage.php';

        $container->services['App\\Auth\\Action\\SignPage'] = $instance = new \App\Auth\Action\SignPage();

        $instance->setContainer(($container->privates['.service_locator.5nX7ca3'] ?? $container->load('get_ServiceLocator_5nX7ca3Service'))->withContext('App\\Auth\\Action\\SignPage', $container));

        return $instance;
    }
}
